markdown: kramdown
permalink: pretty
title: Solawi Oldenburg
baseurl: ""
url: "http://solawi-oldenburg.de"
gems: [jekyll-paginate]
paginate: 2
paginate_path: "/blog/seite:num/"
prose:
  media: 'public/images'
  ignore:
    - _config.yml
    - README.md
    - .gitignore
    - index.html
    - /blog
    - /public/css
    - /public/fonts
    - /public/js
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "published"
        field:
          element: "hidden"
          value: "true"
      - name: "title"
        field:
          element: "text"
          label: "Titel"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Wähle Kategorien"
          placeholder: "Wähle Kategorien"
          options:
            - name: "hof"
              value: "hof"
            - name: "welt"
              value: "welt"              
            - name: "veranstaltung"
              value: "veranstaltung"
    rezepte:
      - name: "layout"
        field:
          element: "hidden"
          value: "recipe"
      - name: "published"
        field:
          element: "hidden"
          value: "true"
      - name: "title"
        field:
          element: "text"
          label: "Titel"
